DROP TABLE PORTFOLIO
;

CREATE TABLE PORTFOLIO
(
  OWNER   VARCHAR(32) NOT NULL, 
  TOTAL   DOUBLE, 
  LOYALTY VARCHAR(8), 
  PRIMARY KEY(OWNER)
)
ORGANIZE BY ROW
;

DROP TABLE STOCK
;

CREATE TABLE STOCK
(
  OWNER       VARCHAR(32) NOT NULL, 
  SYMBOL      VARCHAR(8) NOT NULL, 
  SHARES      INTEGER, 
  PRICE       DOUBLE, 
  TOTAL       DOUBLE, 
  DATEQUOTED  DATE, 
  FOREIGN KEY (OWNER) 
  REFERENCES  PORTFOLIO(OWNER) 
  ON DELETE CASCADE, 
  PRIMARY KEY(OWNER, SYMBOL)
)
ORGANIZE BY ROW
;

DROP TABLE TRADER_LOOKUP
;

CREATE TABLE TRADER_LOOKUP (
  TRADER_USER_NAME      CHAR(25) NOT NULL,
  FK_MERGERDCUSTOMER_ID INTEGER NOT NULL
)
ORGANIZE BY ROW
;

DROP TABLE MERGEDCUSTOMER
;

CREATE TABLE MERGEDCUSTOMER (
  ID                        SMALLINT,
  CHURNRISK                 VARCHAR(6),
  GENDER                    CHAR(1),
  STATUS                    CHAR(1),
  CHILDREN                  SMALLINT,
  ESTINCOME                 DECIMAL(8,2),
  HOMEOWNER                 VARCHAR(1),
  AGE                       SMALLINT,
  TOTALDOLLARVALUETRADED    DECIMAL(9,2),
  TOTALUNITSTRADED          SMALLINT,
  LARGESTSINGLETRANSACTION  DECIMAL(12,4),
  SMALLESTSINGLETRANSACTION DECIMAL(13,5),
  PERCENTCHANGECALCULATION  DECIMAL(6,2),
  DAYSSINCELASTLOGIN        SMALLINT,
  DAYSSINCELASTTRADE        SMALLINT,
  NETREALIZEDGAINS_YTD      DECIMAL(12,4),
  NETREALIZEDLOSSES_YTD     DECIMAL(13,5)
)
ORGANIZE BY ROW
;
DROP TABLE MERGED_DEMOGRAPHICS_TRADING_CUSTOMER
;

CREATE TABLE MERGED_DEMOGRAPHICS_TRADING_CUSTOMER  (
  ID              SMALLINT ,
  CHURNRISK       VARCHAR(6),
  GENDER          CHAR(1),
  STATUS          CHAR(1),
  CHILDREN        SMALLINT,
  ESTINCOME       DECIMAL(8,2),
  HOMEOWNER       CHAR(1),
  AGE             SMALLINT,
  TOTALDOLLARVALUETRADED    DECIMAL(9,2),
  TOTALUNITSTRADED          SMALLINT,
  LARGESTSINGLETRANSACTION  DECIMAL(12,4),
  SMALLESTSINGLETRANSACTION DECIMAL(13,5),
  PERCENTCHANGECALCULATION  DECIMAL(6,2),
  DAYSSINCELASTLOGIN        SMALLINT,
  DAYSSINCELASTTRADE        SMALLINT,
  NETREALIZEDGAINS_YTD      DECIMAL(12,4)
)
ORGANIZE BY ROW
;

DROP TABLE CUSTOMER_OFFER_ACCEPTED
;

CREATE TABLE CUSTOMER_OFFER_ACCEPTED  (
  ID                     SMALLINT NOT NULL PRIMARY KEY,
  GENDER                 CHAR(1),
  STATUS                 CHAR(1),
  TOTALDOLLARVALUETRADED DECIMAL(9,2),
  TOTALUNITSTRADED       SMALLINT,
  OFFER_ACCEPTED         VARCHAR(25),
  OFFER_COST             SMALLINT
)
ORGANIZE BY ROW
;

IMPORT FROM /tmp/02-customerofferaccepted.csv OF DEL SKIPCOUNT 1 REPLACE INTO CUSTOMER_OFFER_ACCEPTED
;

IMPORT FROM /tmp/03-mergedcustomers.csv OF DEL SKIPCOUNT 1 REPLACE INTO MERGEDCUSTOMER
;

IMPORT FROM /tmp/04-mergeddemographicstradingcustomer.csv OF DEL SKIPCOUNT 1 REPLACE INTO MERGED_DEMOGRAPHICS_TRADING_CUSTOMER 
;

IMPORT FROM /tmp/05-traderlookup.csv OF DEL REPLACE INTO TRADER_LOOKUP
;
