DROP TABLE CUSTOMER_ACTIVITY  
;

CREATE TABLE CUSTOMER_ACTIVITY  
(
 ID                          SMALLINT NOT NULL,
 TOTAL_DOLLAR_VALUE_TRADED   DECIMAL(9,2) ,
 TOTAL_UNITS_TRADED          SMALLINT ,
 LARGEST_SINGLE_TRANSACTION  DECIMAL(12,4) ,
 SMALLEST_SINGLE_TRANSACTION DECIMAL(13,5) ,
 PERCENT_CHANGE_CALCULATION  DECIMAL(6,2) ,
 DAYS_SINCE_LAST_LOGIN       SMALLINT ,
 DAYS_SINCE_LAST_TRADE       SMALLINT ,
 NET_REALIZED_GAINS_YTD      DECIMAL(12,4) ,
 NET_REALIZED_LOSSES_YTD     DECIMAL(13,5) 
)
ORGANIZE BY ROW
;

DROP TABLE CUSTOMER_DEMOGRAPHIC  
;

CREATE TABLE CUSTOMER_DEMOGRAPHIC  
(
   ID                        SMALLINT NOT NULL,
   GENDER                    CHAR(1) ,
   STATUS                    CHAR(1) ,
   CHILDREN                  SMALLINT ,
   ESTIMATED_INCOME          DECIMAL(9,2) ,
   HOME_OWNER                CHAR(1) ,
   AGE                       SMALLINT 
)
ORGANIZE BY ROW
;

IMPORT FROM /tmp/06-customeractivity.csv OF DEL SKIPCOUNT 1 REPLACE INTO CUSTOMER_ACTIVITY
;

IMPORT FROM /tmp/08-customerdemographic.csv OF DEL SKIPCOUNT 1 REPLACE INTO CUSTOMER_DEMOGRAPHIC
;

DROP TABLE CUSTOMER_CHURN
;

CREATE TABLE CUSTOMER_CHURN 
(
   ID SMALLINT,
   CHURNRISK VARCHAR(6)
)
;
